# Generated by Django 3.2.20 on 2024-09-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nt_egy_calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyNew1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('square_footage', models.FloatField(default=0)),
                ('gas_usage', models.FloatField(default=0)),
                ('electricity_usage', models.FloatField(default=0)),
                ('miles_driven', models.FloatField(default=0)),
                ('net_co2', models.FloatField(default=0)),
            ],
        ),
    ]
