# Generated by Django 5.1.1 on 2024-09-22 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nt_egy_calc', '0002_energynew1'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
